FROM node:20-alpine3.19

WORKDIR /app

# Update packages and install security updates
RUN apk update && apk upgrade && apk add --no-cache dumb-init

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 3001

# Set Next.js to listen on all interfaces
ENV HOSTNAME=0.0.0.0

# Start development server
CMD ["sh", "-c", "sleep 10 && npm run build:typeorm && npm run migration:run && npm run dev -- -p 3001"]